### PR TITLE
Automatically Publish Docker Image to GHCR.io

### PR DESCRIPTION
**Pull request by ZachNewbery**
This PR looks to add a Github Action that will publish a Docker image for conjure on Github's container repository. Currently, it is scheduled to do automatic publishing on the 1st of Mar at 1am every year (but of course this can be changed as required and is just a placeholder for now).

Currently, the action does not work on my fork due to a unique bug with co-sign which leads to errors when signing due to the uppercase letters in my username. This should not affect the publishing for the main repository should this PR be merged, but may lead to errors if users with uppercase letters in their name fork it. I am currently looking for a fix, but so far many of the proposed fixes do not seem to work as intended. 

Relevant issues (and fixes) I have tried:

- Changing the final line to take ${{ steps.meta.outputs.tags }} instead of the uppercase image name, but this led to issues referenced [here](https://github.com/sigstore/cosign/issues/1568)

An alternative would be removing the signing step entirely, but of course that might lead to security issues.

### CODE REVIEW

**Comment by ozgurakgun** [comment]
Thanks @ZachNewbery. I think it would make more sense to tie this with releases, what do you think? I am planning to make a new release soon as well.

**Comment by ZachNewbery** [comment]
That makes sense! I'll have a look at trying to get an image to publish with each release, alongside a current image that will update as it does now?

**Comment by ChrisJefferson** [comment]
Hi @ZachNewbery , I didn't notice this PR, and made some small changes to the dockerfile. It might be nice to merge these together.

It's good you got the 'signing' to work again, but I wonder if it is really worth fixing, as if github gets hacked enough that 'stack' releases get hacked, then we are in serious trouble! So I might suggest just removing that bit of the code.

**Comment by alex-konovalov** [comment]
Hm, I thought that image signing was just removed, to get shorter but working Dockerfile and then try to restore it if needed - good that it may be not needed at all...

**Comment by ZachNewbery** [comment]
I've just attempted to integrate the changes you made in #509, and removed the signing! I will try to get the new commits to master integrated as well - but other than that I think that should be it mostly ready?

**Comment by ZachNewbery** [comment]
Hi @ozgurakgun @ChrisJefferson just letting you know that I think this PR should be ready for review now! I've added in all the changes made in #509, and it seems to work in terms of publishing on my fork - the only issue seems to be the two checks on the conjure CI :)

**Comment by ozgurakgun** [comment]
Directories to cache would be:

- ~/.ghc
- ~/.cabal
- ~/.stack
- ~/.local/bin
- .stack-work

**Pull request merged**
