### PR TITLE
Update docker-publish.yml to include some basic caching

### PR DESCRIPTION
**Pull request by ZachNewbery**
Add caching to build-push-action, and remove unnecessary workflow steps. Also adds a ccache setup step, to help speed up build times.

### CODE REVIEW

**Comment by ozgurakgun** [comment]
Should I merge this? @ChrisJefferson

**Comment by ChrisJefferson** [comment]
This looks fine to me if it doesn't break the build

**Comment by alex-konovalov** [comment]
Hmm... but it breaks?

**Comment by ZachNewbery** [comment]
It seems to pass the docker building check, not sure if the other checks breaking are something that are caused by the changes or if it's something else?

**Comment by ozgurakgun** [comment]
it's not you, it's me :)

**Pull request merged**
