### PR TITLE
New solver build method

### PR DESCRIPTION
**Pull request by ChrisJefferson**
This switches how solvers are built, so:

a) You can build solvers in parallel (to use even more CPUs)

b) The default "make solvers" just uses one thread, which is slow but safe.

Note: you probably don't want to run "make -j solvers", as that builds all solvers in parallel, with every solver also running with maximum parallelization. I'd be impressed if any machine likes that :)

I also fixed a bug (for me) in installing savile row, when it is already installed.

### CODE REVIEW

**Comment by ChrisJefferson** [comment]
Completely new way of controlling paralleisation, also mentioned in docs and used in docker container.

**Comment by ChrisJefferson** [comment]
Put a new savilerow in the same PR

**Comment by ozgurakgun** [comment]
SR version is fine, I had to compile using an old JVM in the past to make sure it works on all machines. Not sure where you compiled?

**Comment by ChrisJefferson** [comment]
I compiled in java 11. I just tried switching back to 8, but it didn't work as in January Pete added a `--release 8` flag, which makes Java compile in a "java 8" compatible way, except that flag doesn't work in actual java 8 :)

**Pull request merged**
