### PR TITLE
Proofreading, minor changes

### PR DESCRIPTION
**Pull request by felixvuo**
Fixed a couple of grammar issues, made references to keywords and variable names consistently use code markup (like the live conjure tutorials).  Also fixed a dodgy `given`.

### CODE REVIEW

**Comment by ozgurakgun** [comment]
@ott2 - we can merge this one (on top of docsday) if you like

**Comment by ozgurakgun** [comment]
Thanks @felixvuo !

**Comment by ozgurakgun** [comment]
@ott2 - Can we merge this and #498 before we finalise #496?

**Comment by ott2** [comment]
This one looks good.

**Comment by ozgurakgun** [comment]
Thanks Felix!

**Pull request merged**
