### PR TITLE
change expected output of test

### PR DESCRIPTION
**Pull request by fraser-dunlop**
Fix for #475

I think this probably wasn't noticed when the change was made since it is a long running test. But Azure picked it up!

### CODE REVIEW

**Comment by ozgurakgun** [comment]
Why does Azure not fail if this test fails? We should fix that.

**Comment by ozgurakgun** [comment]
I also run all tests on babbage periodically - strange...

**Comment by fraser-dunlop** [comment]
> Why does Azure not fail if this test fails? We should fix that.

It looks like Azure fails to me...

**Comment by fraser-dunlop** [comment]
All tests passing. Let's merge this

**Pull request merged**
