### PR TITLE
documentation updates

### PR DESCRIPTION
**Pull request by ott2**
These changes restructure the documentation, add several pages on Essence expression syntax and semantics, and add ``{`` and ``}`` support to the lexer for Essence documentation.   See also separate comments on some of the individual commits.

### CODE REVIEW

**Comment by ozgurakgun** [comment]
Hi @ott2 - if you are happy with this I will merge it as is.

**Comment by ott2** [comment]
There are some remaining question marks (which I'd appreciate comments about) but otherwise this is approaching a steady state and could be committed as-is.  The Travis build failures seem to relate to timeouts, not sure how to get around those.

**Comment by ozgurakgun** [comment]
Travis builds do not matter for this since it is a documentation only change. I'll see if I can disable them.

**Comment by ott2** [comment]
It seems `welcome.rst` was not committed, fixing.
Now generating `conjure-help.txt` via `mkhelp` script, for all document formats, replacing `conjure-help.html` which only worked for html and was out of date (removed it).

**Comment by ozgurakgun** [comment]
About the mkhelp script: do we still get the html output for the web? I assume we do, but just wanted to make sure.

Why was `references` renamed to `zreferences`? I assume that must be something to do with alphabetical ordering, but I thought listing them in a user specified order under toctree already achieved that. I may easily be missing something...

**Comment by ozgurakgun** [comment]
(Merged anyway, we can make changes in future PRs if we like.)

**Comment by ott2** [comment]
Yes, the mkhelp script turns the conjure help output into basic RST, which then is turned into whatever Sphinx can output.  I'm testing with singlehtml, html, and latexpdf but other formats should work too.

If we are happy with it, then it should probably be included as part of the build sequence for release builds, so that the build id at the top matches; for source and binary releases the RST output would be sufficient.

**Comment by ozgurakgun** [comment]
Did you see [this](https://github.com/conjure-cp/conjure/blob/e935af07f067868d41513aa66e747908b30ef042/docs/Makefile#L218-L223)?

Also, [the old rendering](http://conjure.readthedocs.io/en/v2.0.0/cli.html#help-output) vs [the current one](https://conjure.readthedocs.io/en/latest/cli.html#help-output) for comparison.

The current one is plain text included verbatim, right?

**Comment by ott2** [comment]
Thanks for pointing this out, I missed the Makefile handling: I'll modify the Makefile to match.

In terms of formatting, instead of splitting out columnar text so that RST formatting can be applied, it would probably be easier to generate the in-docs and in-code messages from a common input file.  Are you strongly attached to either format?  (In my force-large-fonts browser setup both come out problematic when rendered in Firefox; the formatted one has the first column on screen and the second mostly off screen, while the verbatim one is in a textbox that is too narrow and has to be scrolled too.  Both look fine in Lynx.)

**Pull request merged**
