### PR TITLE
Hz66 404 patch 2

### PR DESCRIPTION
**Pull request by hz66-404**

### CODE REVIEW

**Comment by hz66-404** [comment]
omg I dont know why it shows all the commits here when I pull the requests

**Comment by hz66-404** [comment]
@N-J-Martin fixed the documentation conflicts, plz have a look, many thanks!

**Review by N-J-Martin — APPROVED** [review]
this looks good to me!

**Comment by ozgurakgun** [comment]
I think we can provide more help and/or write some documentation about forking, keeping a fork up to date etc to avoid earlier commits from being shown in a PR. Let's discuss today.

**Comment by N-J-Martin** [comment]
just checked the links work- they do!

**Pull request merged**
