### PR TITLE
Enumerated type operators documentation

### PR DESCRIPTION
**Pull request by hz66-404**

### CODE REVIEW

**Comment by ozgurakgun** [comment]
I guess this needs a review by @N-J-Martin? Also, let's please please please check the links once these PRs are merged. We don't systematically (programmatically) check them at the moment and that worries me a bit.

**Comment by hz66-404** [comment]
Nadine has seen it before I make a PR to Conjure-cp, I will doublecheck the link after merging it.

**Comment by ozgurakgun** [comment]
should the notebook not be under docs/notebooks?

**Comment by hz66-404** [comment]
it should be under docs/notebooks

**Comment by hz66-404** [comment]
oh Now it seems to be under in docs not in notebooks.

**Comment by hz66-404** [comment]
I have updated that

**Pull request merged**
