### PR TITLE
Fixed typo from PR #598 and documentation bits for set operators

### PR DESCRIPTION
**Pull request by N-J-Martin**
found a mistake in the links for the this notebook, should be corrected now @hz66-404 is welcome to have another look to be sure I caught everything!

### CODE REVIEW

**Comment by ozgurakgun** [comment]
OK, I'll wait until @hz66-404 has a chance to take a look. Thanks!

**Comment by hz66-404** [comment]
Thanks! Just a small issue, can you modify the L_Plus heading to a single #

**Comment by N-J-Martin** [comment]
It is like that now?

**Comment by hz66-404** [comment]
I'm not quite sure, I see no change on my side.

**Comment by N-J-Martin** [comment]
The set operators written by @hz66-404 have been added too.

**Comment by ozgurakgun** [comment]
Thanks both! Is this ready to be merged? Can I ask again for you to check these after we merge them (especially the links).

**Comment by hz66-404** [comment]
set operators part is ready, I will double check this after merging them!

**Comment by hz66-404** [comment]
The link is working fine!

**Pull request merged**
