### PR TITLE
Create letting.md

### PR DESCRIPTION
**Pull request by hz66-404**
add 'letting" doc

### CODE REVIEW

**Comment by ozgurakgun** [comment]
I wrote my comment on #589 before seeing this - I do think the example here works better.

**Comment by ozgurakgun** [comment]
@N-J-Martin may I suggest you review each others work on this?

**Comment by N-J-Martin** [comment]
is there a way that we can have a middle point we can commit to, so we can check that we're both happy before making the PR to you?

**Comment by ozgurakgun** [comment]
I don't think there is when you are using the web interface. But if you fork, clone, make a branch, you both can work on that branch for as long as you like and then make a PR. One of you could fork and give the other one write access.

**Comment by N-J-Martin** [comment]
I've invited @hz66-404 to colab on my fork. We'll try to talk before or during the meeting.

**Comment by ozgurakgun** [comment]
closing these PRs - assuming you will make a PR once you are ready that has a bunch of changes at the same time. please feel free to reopen!

**Pull request closed without merging**
