### PR TITLE
Matrix domains 

### PR DESCRIPTION
**Pull request by N-J-Martin**
adding a page and notebook for matrix domains.

### CODE REVIEW

**Comment by ozgurakgun** [comment]
I tried to add @hz66-404 but I couldn't add them either, but the comment should have notified them...

**Comment by hz66-404** [comment]
I can see it!

**Comment by ozgurakgun** [comment]
Let us know please @hz66-404 when you had a chance to review these.

**Comment by hz66-404** [comment]
The matrix part looks good to me!

**Pull request merged**
