### PR TITLE
Escape more characters in JSON output. Fixes #517

### LINKED ISSUE #517: Error: Malformed JSON in a cached Essence Prime model
Got this error, and it seems like there's two things wrong with Conjure's output:
- `/\` and `\/` have unescaped backslashes. 
- Conjure actually writes data that doesn't conform to its own schema, see 7th entry in trailRewrites array, the "rule" is an array, but must be a string to be read back in. Manually joining the string with \n resolves the issue, so I would suggest that as a solution.

See https://replit.com/@SuperMikal/Conjure-and-Essence-20220507#feedback/bad-json/stdout and the model in the same folder.

### PR DESCRIPTION
**Pull request by stylpe**
#517 

Disclaimer: This was implemented entirely using GitHub Codespaces (without sufficient RAM to build the whole project) on my mobile phone during toilet breaks with zero experience in Haskell. Please be gentle!

### CODE REVIEW

**Comment by stylpe** [comment]
Ah, small mistake in the commit message, I meant to note that it only addresses the first point about the backslashes.

Also, I haven't checked if there's anywhere else where escaping is performed, which could lead to double escaping. Trusting the unit tests will catch that. (Maybe I should add my own unit test even)

**Comment by ozgurakgun** [comment]
Can you see the CI output @stylpe ? After clicking a few times, I get to this page: https://dev.azure.com/conjure-testing/conjure/_build/results?buildId=442&view=logs&jobId=b227660a-cc34-513e-56b6-a239a911c194&j=b227660a-cc34-513e-56b6-a239a911c194&t=778185b6-24a8-5c4e-9ea7-ecd373f7924f

**Comment by stylpe** [comment]
Yep, already made one amendment based on the CI logs :) 

The error message is particularly helpful this time, it correctly suggests `T.singleton` as a fix! Will commit and push in a moment.

**Comment by stylpe** [comment]
Ha, speaking of insufficient RAM, you might need to size up the builders: 

`ghc.exe: getMBlocks: VirtualAlloc MEM_COMMIT failed: The paging file is too small for this operation to complete.
`

**Comment by ozgurakgun** [comment]
The windows builder on Azure has been unreliable, yes. The linux/max ones should work fine I am hoping.

**Comment by stylpe** [comment]
Here's a minimal failing repro model, but I'm not 100% sure where to add it, is tests/pretty_print/issues/ ok?

```
$ The variant triggers refinement output that is vulnerable to the bug
find x : variant {i:int(1..3),b:bool}
$ The backslash at the end of the next line doesn't get eacaped, producing "... /\"
such that active(x,i) -> x[i]>2 /\
x[i]<5

$ Simpler cases that fail since `\ ` isn't a valid JSON escape sequence
find y:bool such that y /\ true
find z:bool such that and([z,true])
```

**Comment by ozgurakgun** [comment]
The parse_print directory is quite specialised for testing the roundtrip: parse/print/parse is the same as parse.

You can put it under `tests/custom/issues/519` if you like? You'll have to put a run.sh file in there as well.

**Comment by stylpe** [comment]
I learned how to use `git rebase -i`, so I fixed up the branch a bit. The added test is a blind commit again, so relying on CI for feedback, otherwise I consider this ready!

**Comment by stylpe** [comment]
This time it should be OK!

**Comment by ozgurakgun** [comment]
Thanks for the contribution @stylpe!

**Pull request merged**
